server:
  port: 9092

#Nos configurations
mes-configs:
  dureePret: 4

# Email
spring:
  main:
    banner-mode: off
  application:
    name: service_batchmail
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          starttls:
            enable: true

